### ISSUE TITLE
The main file.js at the root of the project

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/microbe-web#10]
Colleagues, please take a look, should it be there or should it be moved to the www directory?

**Comment by themactep** [comment]
That is some code that at some point was used for prototyping, then
removed/replaced/set aside but still can be used further down the road. No
need to put it into production.

Let's move it to a new branch, call it "dirty" or something, for storing
and sharing between machines, but unreachable for a layman.

**Comment by ZigFisher** [comment]
I think it can be stored both in the main branch and in development, it's just that all files that are not used in production should be in the "tools, libs, garbage" directory or some similar one, but not in the root. Any directory name will do.

**Comment by themactep** [comment]
done.
