### ISSUE TITLE
Проблемы с обновлением.

### ISSUE THREAD

**Issue by fadermix** [OpenIPC/microbe-web#105]
Gk7205v300 inx335 winbond, последний бут.
Свернул вкладку с обновлением, получил кирпич.
Возможно это не связано с закрытием вкладки.
![IMG_20221111_091721](https://user-images.githubusercontent.com/74561052/201276057-30d9b883-295b-4971-9241-6d301330ceac.jpg)
![IMG_20221111_091712](https://user-images.githubusercontent.com/74561052/201276061-94daf02d-99ef-4dec-9af3-8d0ecaf06340.jpg)
На 85 порту все 404, ssh не дает коннект, 80 не запущен стример.

UPD: обновление прерывается с закрытием вкладки с веб интерфейсом

**Comment by themactep** [comment]
все закономерно. закрытие таба ведет к убиению процесса. не закрывай таб пока апдейт не завершен.
