### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by longcat99** [OpenIPC/microbe-web#107]
bug: SOCKS5
 Ports other than 1080 cannot be set.  The password show and hide buttons are invalid and the domain name cannot be saved.
 In addition, the file manager cannot select the upper level directory.  The latest firmware version, Web Interface version is dev 11-5.  Web Interface Update script fails to update.

ошибка: SOCKS5
 Порты, отличные от 1080, не могут быть установлены.  Кнопки отображения и скрытия пароля недействительны, и доменное имя не может быть сохранено.
 Кроме того, файловый менеджер не может выбрать каталог верхнего уровня.  Последняя версия прошивки, версия веб-интерфейса — dev 11-5.  Веб интерфейс
 Скрипт обновления не обновляется

bug：SOCKS5
 无法设置除1080以外的端口。 密码显示和隐藏按钮无效，不能保存域名。
 另外文件管理器不能选择上一级目录。 固件版本最新，Web Interface版本为dev 11-5。 Web Interface更新脚本无法更新

**Comment by themactep** [comment]
I believe it was fixed. Please reopne if it is not.
