### ISSUE TITLE
MQTT to QGC

### ISSUE THREAD

**Issue by longcat99** [OpenIPC/microbe-web#108]
Enhanced function to interpret the domain name or ip address and port in the message content by subscribing to the mqtt topic.  Send udpsink to the target.  Application with qgc ground station

**Comment by themactep** [comment]
Could you please elaborate what kind of information and in what format you need to send via MQTT? Please provide an example. Thank you.

**Comment by themactep** [comment]
More info needed. Feel free to reopen with additional information.
