### ISSUE TITLE
With OpenIPC : Motion guard sensitivity KO

### ISSUE THREAD

**Issue by darkfuncat** [OpenIPC/microbe-web#113]
Hi,
Another report with OpenIPC.
The sensibility of motion guard is extrem, event with motion sensitivity to 1 (of 1-50)
I guess that this control does nothing.
Is there any action to control the real sensitivity ?
Thanks

**Comment by themactep** [comment]
Motion sensitivity slider is a semi-functional dud that works for most but not all. It defines thrashold as a number of zones triggered in a motion alert. Afaik the formula behind it is 51 minus slider value, meaning full to the right will set number of zones to one, and full to the left would set it to 50. You need to check syslog to see what is your real range of zones triggered with a motion, and set the thrashold accordingly, maybe directly in config file, not in the web form.

**Comment by themactep** [comment]
Kinda irrelevant after switching to a new motion detection routine. Please open a new ticket if the problem reappears.
