### ISSUE TITLE
Microbe dev version dev+374a87b, 2022-11-23 change IP doesn't stick

### ISSUE THREAD

**Issue by ddemos1963** [OpenIPC/microbe-web#114]
Using static IP (Use DHCP off) Web interface under Settings, Network, enter new IP in Ip Address box, click Save. Green banner at the top says "Network Settings Updated" however the old IP now shows again in the IP Address box and the settings didn't stick. In the attached photo, Trying to change 192.168.0.196 to 192.168.0.146. Stable Microbe version functions normal for this. Thanks for your help.
![IP_Change](https://user-images.githubusercontent.com/120747740/208169159-de4e2abd-ba03-4a3d-9f8c-d7f5411965df.png)

**Comment by themactep** [comment]
Did you try to reboot the camera afterwards? Setting shown are taken from the active connection. There should be a banner on top of the window asking to reboot the camera to apply the changes.

**Comment by ddemos1963** [comment]
The reboot button does not show up as it does in stable, just the green
network settings updated banner showed up. I did go to settings, reset,
reboot and rebooted from there. The old IP was still in effect.

**Comment by themactep** [comment]
networking was rewritten recently. please reopen if it still an issue.
