### ISSUE TITLE
Change ZeroTier plugin launch

### ISSUE THREAD

**Issue by FlyRouter** [OpenIPC/microbe-web#117]
At the moment when calling ZeroTier plugin in custom firmware based on `lite` the following error occurs.
`ZeroTier plugin is not supported on OpenIPC lite.`
However this is custom firmware, ZeroTier is there and works.
I propose to make check linking not by `lite/ultimate` profile but by actual presence of binary file, for example `/usr/sbin/zerotier-cli`.
Thank you !

**Comment by themactep** [comment]
done. test it and see if it works for you now.

**Comment by themactep** [comment]
please reopen if it is still the case.
