### ISSUE TITLE
File Manager back link

### ISSUE THREAD

**Issue by ANTPro** [OpenIPC/microbe-web#120]
В вебморде не правильно генерируются ссылки назад:
сейчас: http://192.168.1.100/cgi-bin/file-manager.cgi?cd=/dev/..
должно быть: http://192.168.1.100/cgi-bin/file-manager.cgi?cd=/

**Comment by themactep** [comment]
И чем одна отличается от другой? Оба пути ссылаются на корень.

**Comment by ANTPro** [comment]
> И чем одна отличается от другой? Оба пути ссылаются на корень.

Первая не работает (в хроме например)

**Comment by themactep** [comment]
работает и в хроме, и в ff

https://user-images.githubusercontent.com/37488/221678305-1bfc97f9-1715-4bd6-b33b-8e3f304d27b1.mp4

**Comment by ANTPro** [comment]
Может от версии прошивки зависит? У меня: gk7205v300 (gk7205v200 family), imx335, 16 MB nor flash, 2.3.02.11-ultimate, openipc-gk7205v300

**Comment by themactep** [comment]
у меня нет такого железа, я не смогу проверить на такой же камере. нужен кто-то с такой же камерой и прошивкой, чтобы проверить, что это не проблема конкретного сетапа.

**Comment by ANTPro** [comment]
Обновление вебморды не помогло. У меня сейчас все стоит последнее с репозов(собирал сам из исходников):
Web Interface
Version
Installed
master+a7bc583, 2023-02-06
Stable
[master+a7bc583, 2023-02-06](https://github.com/OpenIPC/microbe-web/commits/master)

System
Firmware
Version
2.3.03.01-ultimate
Build
+, 2023-03-01
Majestic
master+cf96460, 2023-02-27
Hostname
openipc-gk7205v300

**Comment by themactep** [comment]
А чего ее обновлять, если там последние изменения месячной давности. Это не проблема веб интерфейса, в нем все работает. Это может быть проблема виндовой версии браузера. Никакие плагины, прокси и прочие прослойки между браузером и камерой не установлены?
