### ISSUE TITLE
Enhancement On/Off illumination

### ISSUE THREAD

**Issue by ANTPro** [OpenIPC/microbe-web#121]
Если настроить: GPIO pin to turn on night mode illumination
То нельзя будет его отключить (только если указать не верный пин)
Предложение добавить checkbox дающий возможность отключать использование подсветки.

**Comment by themactep** [comment]
не вижу проблемы. значение убирается если записать пустое поле.

https://github.com/OpenIPC/microbe-web/assets/37488/b6e23e28-4400-4852-b9f2-c2581b36f625
