### ISSUE TITLE
Пароль в webui-settings.cgi

### ISSUE THREAD

**Issue by ANTPro** [OpenIPC/microbe-web#122]
Обрезается вывод пароля если он содержит $

**Comment by themactep** [comment]
Что где обрезается?

![Screenshot from 2023-02-27 15-35-57](https://user-images.githubusercontent.com/37488/221679739-38dda2c5-8287-4cb6-a95c-af97a3234655.png)

**Comment by ANTPro** [comment]
![image](https://user-images.githubusercontent.com/273104/221689631-d4de0d96-ff8b-4bad-8a86-6c00ee5b44c1.png)

**Comment by themactep** [comment]
что я из этого должен понять? мне нужна не (только) картинка, но и описание и порядок действий, которые объяснят, что и где не работает, чтобы я мсог посторить их на своей машине, получить ту же ошибку, и поправить ее.

**Comment by ANTPro** [comment]
Штатно обновил вебморду, не починилось:
Web Interface
Version
Installed
master+a7bc583, 2023-02-06
Stable
[master+a7bc583, 2023-02-06](https://github.com/OpenIPC/microbe-web/commits/master)
Unstable
[dev+fc283a1, 2023-02-10](https://github.com/OpenIPC/microbe-web/commits/dev)

**Comment by ANTPro** [comment]
Задать пароль с $ и перейти на webui-settings.cgi и отобразится, то что на скрине(нет части пароля).

**Comment by ANTPro** [comment]
Нашел баг, в common.cgi
```
не правильно:   for _v in $_vars; do eval "echo ${_v}=\\\"\$${_v}\\\">>${_tmpfile}"; done
правильно:   for _v in $_vars; do eval "echo ${_v}='\\\"\$${_v}'\\\">>${_tmpfile}"; done
```

**Comment by themactep** [comment]
проблема не в том, как это парсится в sysinfo.txt, там как раз все отображается корректно, а в том, как пароль с `$` подставляется в `<input type="password">`

**Comment by themactep** [comment]
обнови web ui из dev ветки, и проверь, что теперь работает пароль.

**Comment by ANTPro** [comment]
```
Web Interface
Version
Installed
dev+91fb323, 2023-03-03
```
Работает, спасибо!
