### ISSUE TITLE
MQTT topic ASCII detection bug

### ISSUE THREAD

**Issue by fricy** [OpenIPC/microbe-web#125]
I'm trying to change the MQTT topic from the default openipc/[hostname] to domoticz/cam and the script flags that name as non-ASCII.

> MQTT topic should not include non-ASCII characters.

**Comment by themactep** [comment]
Is topic the only field you are changing?

**Comment by fricy** [comment]
No, but the topic fields are the only ones that trigger this warning.

**Comment by themactep** [comment]
should be good now.

**Comment by themactep** [comment]
please reopen if it is still an issue.

**Comment by MikeVRT** [comment]
2.4.02.19 you still can't use _ or - symbols in the topic string, for example (with the same error message).
But they are ASCII symbols and can actually be used with MQTT
