### ISSUE TITLE
Failed to log in to the web configurator when using a long password with special characters

### ISSUE THREAD

**Issue by kstlv** [OpenIPC/microbe-web#131]
Camera: Rotek Switcam-HS-303
Firmware: OpenIPC_PayWall_HS303V1_v2.2.10.2.tgz

After flashing the camera in the web configurator, I set a very complex password using special characters 100 characters long. Then I couldn't log in to the web configurator because the password was not accepted.

The problem probably lies either in the large length of the password, or the special characters contained in the password interfered (perhaps even an injection into the code occurred).

I reflashed, set a normal average password without special characters. Everything worked.

Probably worth adding a check for the length of the password and the presence of prohibited characters in the web configurator.

---

После прошивки камеры в веб-конфигураторе я поставил очень сложный пароль с использованием спецсимволов длиной в 100 символов. Затем я не смог войти в веб-конфигуратор, потому что пароль не принимался.

Вероятно, проблема кроется либо в большой длине пароля, либо помешали содержащиеся в пароле спецсимволы (возможно, даже произошла инъекция в код).

Перепрошил, поставил нормальный средний длины пароль без спецсимволов. Все заработало.

Наверное стоит добавить проверку на длину пароля и наличие запрещенных символов в веб-конфигураторе.

**Comment by themactep** [comment]
authentication is rewritten in dev branch.
