### ISSUE TITLE
No outputVolume and outputGain slider on in majestic audio settings

### ISSUE THREAD

**Issue by jayfan0** [OpenIPC/microbe-web#132]
There are new `outputVolume: ` and `outputGain: ` config options for speaker output that needs to be configurable from the web ui 

outputVolume is int between 0-100
outputGain is looking for a int value between 0 - 31

**Comment by themactep** [comment]
done in dev. please try it out and close the ticket if it works.

**Comment by themactep** [comment]
please feel to reopen if it is still an issue.
