### ISSUE TITLE
Changing passwords for users

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/microbe-web#134]
Please consider changing the password not only for user **root**, but also for the second non-privileged user **viewer**.
If user **viewer** does not exist, then it is worth creating it, and when changing his password, it is advisable to change the hash for the NetIP system.
Thanks

```
adduser viewer -s /bin/false -D -H
echo viewer:123456 | chpasswd
```

**Comment by themactep** [comment]
Added into dev [6447c8d]. Try it out and see if it works for you.
