### ISSUE TITLE
"Telegram Bot" and "Send to Telegram" notice and link

### ISSUE THREAD

**Issue by ialexlog** [OpenIPC/microbe-web#136]
Please consider adding a notification to the telegram bot page (and desirable an internal link like /cgi-bin/plugin-send2telegram.cgi) that the bot is an add-on to the telegram sender, and on the telegram sender page add information about the possibility to configure the bot with an internal link like /cgi-bin/plugin-telegrambot.cgi
It is highly desirable to place these two items next to each other - "Telegram Bot" and "Send to Telegram" - in the "Services" menu from the drop-down menu.
https://t.me/openipc_modding/208430
Thanks!

**Comment by themactep** [comment]
The telegram bot is not an addon, it's an independent entity which can be set to use send2telegram.sh just like any other plugin or a command -  send2yadisk.sh, send2openwall.sh, whatever. Obviously, that any plugin you want to use with the bot should be configured beforehands, including send2telegram.sh. I see no ground for the abovementioned changes.
