### ISSUE TITLE
send2telegram.sh CLI issue

### ISSUE THREAD

**Issue by ialexlog** [OpenIPC/microbe-web#137]
Attempt to execute `send2telegram.sh -t 3166574304:AAFCI2pK12133zT5-SsALw2aVQnnuJd-FfA -c -1001455245266` ends with nothing if `Configuration file /etc/webui/snapshot.conf not found.` which is possible after clearing overlay as example.

Please consider adding a fallback option to the script that prompts what needs to be configured in case settings are absent, whether in the body of the telegram message itself or in the console. Or send picture by default.
https://t.me/openipc_modding/208487
https://t.me/openipc_modding/208505
https://t.me/openipc_modding/208523
Thanks!

**Comment by themactep** [comment]
added a warning message if no method if selected.

![Screenshot from 2023-05-07 02-13-51](https://user-images.githubusercontent.com/37488/236661078-348e0af4-218f-4b95-ae5b-ef2a120ff9c5.png)
