### ISSUE TITLE
Password typo problem

### ISSUE THREAD

**Issue by FunnyGrass** [OpenIPC/microbe-web#154]
Достаточной регулярно в последнее время занимаюсь прошивкой камер на gk7205v200. И в очередной раз при смене пароля с 12345 на свой постоянный допустил опечатку. Теперь для восстановления доступа необходимо заходить в u-boot и перепрошивать образ.
Как вариант, предлагаю добавить поле подтверждение пароля при его смене, это поможет уменьшить количество случаев потери доступа к оборудованию из-за опечаток, невнимательности и других форм проявления человеческого фактора. А время, которое пользователю потребуется на двойной ввод пароля значительно меньше времени, которое требуется на восстановление доступа.

**Comment by themactep** [comment]
нет нужды перепрошивать образ. достаточно очистить оверлей прямо из бута.
https://github.com/themactep/openipc-wiki/blob/master/en/cheatsheet-uboot.md#erase-changes

**Comment by themactep** [comment]
многолетняя практика показывает, что наличие дополнительных полей не помогает. пользователи просто копируют текст в буфер (с ошибкой) и вставляют его в оба поля.

**Comment by FunnyGrass** [comment]
Это конечно идея хорошая, но в таких ситуациях предпочитаю таки вводить пароль с клавиатуры.
И второй момент, не всегда бывает возможность у пользователя зайти в u-boot. 
Если вы не видите необходимости менять это в общем коде, но знаете как и где это сделать, подскажите пожалуйста.
Поправлю в Composer'e.

**Comment by themactep** [comment]
[вот здесь](https://github.com/OpenIPC/microbe-web/blob/57f945c7a0f6998dae5709e0099ba8eea6321de6/files/var/www/cgi-bin/webui-settings.cgi#L97
) надо сделать еще одно поле:
```
<% field_password "ui_password_new_confirmation" "Password Confirmation" %>
```

а [вот здесь](https://github.com/OpenIPC/microbe-web/blob/57f945c7a0f6998dae5709e0099ba8eea6321de6/files/var/www/cgi-bin/webui-settings.cgi#L18-L19) добавить разбор его значения и проверку на совпадение обоих паролей:
```
new_password_confirmation="$POST_ui_password_new_confirmation"
[ -z "$new_password_confirmation" ] && redirect_to $SCRIPT_NAME "danger" "Password confirmation cannot be empty!"
[ "$new_password_confirmation" != "$new_password" ] && redirect_to $SCRIPT_NAME "danger" "Password does not match its confirmation!"
```

**Comment by FunnyGrass** [comment]
Спасибо!
