### ISSUE TITLE
Error in Majestic/Alarm tab

### ISSUE THREAD

**Issue by dioxyde2023** [OpenIPC/microbe-web#168]
In the latest version of the interface there is a problem with displaying settings in the Alarm tab of Majestic page.

**Comment by viktorxda** [comment]
This might be an issue if you switch between stable/dev branch, try to update with the option `Install even if the same version` or clear the overlay.

**Comment by dioxyde2023** [comment]
> This might be an issue if you switch between stable/dev branch, try to update with the option `Install even if the same version` or clear the overlay.

No, I used bundled version.

**Comment by FlyRouter** [comment]
> In the latest version of the interface there is a problem with displaying settings in the Alarm tab of Majestic page.

Please add a couple of screenshots and show what exactly your problem is, and also tell us the type of device.

**Comment by dioxyde2023** [comment]
gk7205v210 (gk7205v200 family), sc223a, 8 MB nor flash, 2.3.09.13-lite

Here's link to screenshot https://ibb.co/552QHKX

**Comment by viktorxda** [comment]
![alarm](https://github.com/OpenIPC/microbe-web/assets/35473052/0af5e602-6a1a-4916-992d-cc4528d19b73)
It was already mentioned, try to reset the overlay or remove the overlay files:
`rm -rf /overlay/root/var`

**Comment by themactep** [comment]
this can be a problem of cached content in browser. try to use ctrl-r or ctlr-f5 to refresh the page bypassing the cache. please let me know if it fixed the issue.

**Comment by dioxyde2023** [comment]
I cleared the browser cache, checked this problem in new browser. All the same!

**Comment by themactep** [comment]
Please open source view of the broken page and make a screenshot of the last lines of code to determine where it breaks. Or save the page as html file and send to themactep@gmail.com, I'll see how to fix it. Thanks.

**Comment by dioxyde2023** [comment]
Here's link to source screenshot https://ibb.co/hfnC1sL

**Comment by dioxyde2023** [comment]
Thanx
