### ISSUE TITLE
Services/Send To FTP

### ISSUE THREAD

**Issue by dioxyde2023** [OpenIPC/microbe-web#193]
Здравствуйте, не создается папка по шаблону в поле FTP path, аналогичному как в имени файла File template. Вместо папки с датой в имени, создается папка с символами шаблона в качестве имени. Прилагаю скриншот раздела в админке. https://ibb.co/M7VZ4F8

**Comment by themactep** [comment]
Так и не планировалась, что бы директория умела понимать шаблоны, только имя файла. Можно попробовать задавать поддирректории непосредственно в имени файла, или дописать преобразование поля директории в скрипте и прислать pr.

**Comment by dioxyde2023** [comment]
Спасибо, прописал поддиректории в шаблон имени файла - сработало.
Шаблон имени файла такой: /%Y/%m/%d/Y%m%d-%H%M%S.jpg
Не совсем удобно выходит. Сделайте там подсказку тогда об этой возможности.

**Comment by dioxyde2023** [comment]
Возможный вариант по дескрипшену к полю "File template"
Прилагаю подправленный скрипт https://pastebin.com/QrVRWNUm

**Comment by themactep** [comment]
Это делается не так. Делаешь форк репозитория, делаешь поправки в своей копии, присылаешь pull request с патчем.

**Comment by dioxyde2023** [comment]
Хорошо.

**Comment by FlyRouter** [comment]
https://github.com/OpenIPC/microbe-web/pull/194#issuecomment-1774166309

**Comment by dioxyde2023** [comment]
Поддерживаю!

**Comment by dioxyde2023** [comment]
Предлагаю такой вариант: https://github.com/dioxyde2023/microbe-web/blob/master/files/var/www/cgi-bin/plugin-send2ftp.cgi

**Comment by themactep** [comment]
https://github.com/OpenIPC/microbe-web/blob/f63a6f48d75ec9a90332a07044ec058467f16943/files/usr/sbin/send2ftp.sh#L66-L67

Вот здесь видно, что та часть, которая `ftp_template,` прогоняется через `date` и получает значения вместо переменных, а статичная часть, которая `ftp_path,` парсится на предмет замены пробелов. Если слить обе части вместе и потом прогонять через `date,` то при наличии пробелов в статичном пути, замененных на `%20`, мы получим бедлам и ошибку. Не надо придумывать проблем, там где их нет, и всё и так работает.

**Comment by dioxyde2023** [comment]
Можно просто добавить описание для поля  ftp_template: "тут можно можно использовать не только имя файла, а еще и подкаталоги, в которых можно использовать strftime()"  Я себе вот так прописал: /%Y/%m/%d/camshot-%Y%m%d-%H%M%S.jpg
[Пример.](https://ibb.co/C5JCwBq)
Но в том виде как сейчас мало кто догадается, что в имени файла можно прописать пути к подкаталогам.
Не надо ничего сливать. Оставьте все как есть, просто нужно внизу под полем File template дописать, что можно в этом шаблоне вписать поддиректории, в имени которых можно так же использовать strftime(). Вы же мне это и подсказали. Просто это знаете только вы, как разработчик, а другие с трудом догадаются.

**Comment by themactep** [comment]
я уже писал, что добавлять в описание чего именно можно делать мы не будем. потому что можно делать все. в том числе и использовать слэш как часть имени файла в шаблоне. можно еще цифры использовать, запятые и тире, об этом тоже надо отдельно писать?

**Comment by dioxyde2023** [comment]
Тогда можно дописать ссылку на страницу в вики про это.

**Comment by themactep** [comment]
нет.
