### ISSUE TITLE
Предложение по доработке страниц в сервисах по отправке снапшотов

### ISSUE THREAD

**Issue by dioxyde2023** [OpenIPC/microbe-web#201]
Здравствуйте, предлагаю добавить тумблер "Use HEIF format." в сервисах отправки снапшотов, по аналогии с сервисом Send to OpenWall. Это даст возможность отображать OSD в снапшоте. Если сохранить снапшот по этому эндпойнту http://IP/image.heif то OSD отображается. Так же можно добавить описание, что при использовании HEIF format отображается OSD на снапшоте.

**Comment by FlyRouter** [comment]
I support this feature, it is actual for Hisilicon processors first of all.

**Comment by themactep** [comment]
в какой-то конкретный сервис? у нас их много.

**Comment by dioxyde2023** [comment]
Send to Telegram, Send to FTP, MQTT client, Send to email, Send to Webhook, Send to Yandex Disk.

**Comment by ZigFisher** [comment]
Снапшоты на Hisilicon и Goke, в зависимости от модели, не содержат OSD.
Поскольку HEIF мы грабим уже непосредственно с канала RTSP в котором всё есть, там всегда будут все маски приватности и OSD. Фича интересная, можно сохранить в список хотелок. С HEIF не только по этому вопросу нужно разбираться, а так у нас будет уже инструментарий для этого получения, т.е. увеличиваются шансы что будут использовать не только админы эту возможность. Спасибо.

**Comment by dioxyde2023** [comment]
При разрешении 5 Mp снапшот в Jpeg с качеством 50 занимает места на диске около 1 Мб, а heif - около 200 Кб. Это создает нагрузку на сеть при работе Motion guard, а при использовании формата heif можно значительно сократить пропускную способность канала для других задач, особенно когда это мобильная связь. Телеграм этот формат понимает и даже конвертирует его в Jpeg. В других случаях можно воспользоваться программами конверторами.

**Comment by themactep** [comment]
я могу сделать глобальную настройку для всех сервисов разом, а могу для каждого индивидуального. чем, собственно, и был вызван вопрос.

**Comment by dioxyde2023** [comment]
Лучше сделать раздельными. Телеграм умеет отрывать, а на FTP без какого скрипта или софтины можно и не открыть при случае.

**Comment by themactep** [comment]
логично. хорошо, добавлю на днях.

**Comment by themactep** [comment]
done in dev branch.
