### ISSUE TITLE
Changing hostname not possible

### ISSUE THREAD

**Issue by jangrewe** [OpenIPC/microbe-web#202]
Hi, i'm not sure if this is a firmware or webinterface issue, but i'm not able to update the camera's hostname via the webinterface.

Changing it via SSH in /etc/hostname and /etc/hosts works, but that makes the option in Settings -> Network pointless. :-)

**Comment by themactep** [comment]
@jangrewe, i pushed some changes to dev branch. please test and report if it works for you. it's better to have a uart connected while trying this, just in case :)

**Comment by themactep** [comment]
No reply for a month. Closing as stale.
