### ISSUE TITLE
Add ability to analyze width and height of detected area at "plugin-motion.cgi" page.

### ISSUE THREAD

**Issue by dioxyde2023** [OpenIPC/microbe-web#214]
Hello, it will be great if you add 4 fields called [analyze min region height ], [analyze max region height ], [analyze min region width] and [analyze max region width ]  at "plugin-motion.cgi" page and add checkbox to switch it off.
Also add ability into /usr/share/openipc/motion_detect.sh script to trigger only if detected area is in pointed analyzing dimensions of region. Example you can see [here](https://github.com/OpenIPC/sandbox/blob/main/scripts/motiondetect/motion_detect_custom.sh).

**Comment by FlyRouter** [comment]
Good idea, thank you

**Comment by themactep** [comment]
While I can inderstand setting limits on dimentions, the second part of the request... isn't it what ROI does?

**Comment by dioxyde2023** [comment]
No, sometimes detected area is smaller or bigger than ROI. Why, I don't know.

**Comment by themactep** [comment]
Then it sounds like a bug and should be addressed in detection code. Repeating in bash the math what has to be done in silicon is a bad idea.

**Comment by dioxyde2023** [comment]
Not exactly, if detected object is smaller then ROI it's not a Bug, I think. Here's a [picture ](https://paste.pics/PUIV4)of my thoughts.

**Comment by dioxyde2023** [comment]
Or it must do Majestic not script, but settings in web should be for this too.

**Comment by themactep** [comment]
I've added min/max zone size and the number of objects. Please test and report results.
https://github.com/OpenIPC/microbe-web/commit/00641bc455b234747d057e56aa77f638ca82d3f7

**Comment by dioxyde2023** [comment]
Ok, thank you!

**Comment by dioxyde2023** [comment]
![50x50](https://github.com/OpenIPC/microbe-web/assets/142792025/a7e5cb57-fad4-44dd-9b12-32d047de2e01)

It triggers even at 50 width and 50 height, but in settings min width and min height are 270.

**Comment by dioxyde2023** [comment]
Also the Minimum zone height field description is incorrect
![field](https://github.com/OpenIPC/microbe-web/assets/142792025/3dea4cb1-381b-4288-811d-f2e4a70b56f7)

**Comment by themactep** [comment]
While discussing this with other developers, I came to the conclusion that this functionality is rather misleading, as the reported size and position do not correspond to all objects, but only to the first one.

I have removed any size calculation from the Web UI and the corresponding script.
