### ISSUE TITLE
Problem in update S95majestic. Version  dev+12721b4, 2023-12-09

### ISSUE THREAD

**Issue by khseal** [OpenIPC/microbe-web#228]
No start daemon after boot camera.
Manual start.

> root@openipc-hi3516cv300:~# /etc/init.d/S95majestic start 
> 
> hisilicon: Loading video system has started...
> Starting majestic: start-stop-daemon: option requires an argument: s
> BusyBox v1.36.1 (2023-12-12 07:25:40 UTC) multi-call binary.
> 
> Usage: start-stop-daemon [OPTIONS] [-S|-K] ... [-- ARGS...]
> 
> Search for matching processes, and then
> -K: stop all matching processes
> -S: start a process unless a matching process is found
> 
> Process matching:
> 	-u USERNAME|UID	Match only this user's processes
> 	-n NAME		Match processes with NAME
> 			in comm field in /proc/PID/stat
> 	-x EXECUTABLE	Match processes with this command
> 			in /proc/PID/cmdline
> 	-p FILE		Match a process with PID from FILE
> 	All specified conditions must match
> -S only:
> 	-x EXECUTABLE	Program to run
> 	-a NAME		Zeroth argument
> 	-b		Background
> 	-N N		Change nice level
> 	-c USER[:[GRP]]	Change user/group
> 	-m		Write PID to pidfile specified by -p
> -K only:
> 	-s SIG		Signal to send
> 	-t		Match only, exit with 0 if found
> Other:
> 	-o		Exit with status 0 if nothing is done
> 	-v		Verbose
> 	-q		Quiet
> FAIL

Problem in DAEMON_ARGS="-s"

**Comment by themactep** [comment]
try to update from dev repo and see if it works now.
