### ISSUE TITLE
Размер пакета и количество пингов по умолчанию

### ISSUE THREAD

**Issue by cronyx** [OpenIPC/microbe-web#24]
Monitoring Tools:

Oops. Something happened.

# ping -c 15 -s 1500 4.2.2.1

PING 4.2.2.1 (4.2.2.1): 1500 data bytes

--- 4.2.2.1 ping statistics ---
15 packets transmitted, 0 packets received, 100% packet loss

Было бы не плохо изменить размер пакета по умолчанию на 1450, так как 1500 не пролезет в туннели c MTU менее 1500.

**Comment by ZigFisher** [comment]
Поддерживаю коллегу.

В дефолте установка размера пакета должена отсутствовать. т.е. соответствовать свойствам интерфейса.
Так-же прошу снизить количество пакетов до 5 ибо 15 это уже долго и зачастую не нужно
Идеально-бы было вынести размер и количество в отдельные насттраиваемые поля.
Спасибо.

**Comment by themactep** [comment]
done.
