### ISSUE TITLE
Write new settings through temp file in majestic-settings.cgi

### ISSUE THREAD

**Issue by p0isk** [OpenIPC/microbe-web#3]
Use temp yaml file in tmpfs in 'for' updating cycle.
Write to /etc/majestic.yaml at the end of script for decreasing flash writes

**Comment by themactep** [comment]
@ZigFisher, is yaml-cli capable to write to a temp file/read from a batch file?

**Comment by ZigFisher** [comment]
I think there is no such function yet.
However, @p0isk takes part in the modification of the yaml-cli and I think this will not be a problem in the future.

**Comment by p0isk** [comment]
Done.
https://github.com/OpenIPC/microbe-web/commit/738b1237d0dc02b8f04afb999ee32f53c0d676a4
