### ISSUE TITLE
It is not possible to set a login and password for the RTSP stream via the web interface

### ISSUE THREAD

**Issue by solalex1** [OpenIPC/microbe-web#42]
At the same time, there is such an opportunity for NETIP.

**Comment by solalex1** [comment]
Версия dev+ea14031, 2022-05-14
При попытке записать из веб логин-пароль в RTSP, в конфиг мажестика записывается только строка логина, пароля нет и после этого мажестик перестает стартовать 
11:21:05 [app_conf] parse_app_config@578          RTSP username and password must either both exist or both absent.
11:21:05 [    main] main@203                      Parsed failed, check config
11:21:05 [    main] main@223                      Shutdown main thread

**Comment by themactep** [comment]
Что выдает экран сравнения конфигов после установки пароля? Я проверил на своем сетапе -- пароль записывается в конфиг.

![Screenshot_2022-05-16-12-34-50-534_com android chrome](https://user-images.githubusercontent.com/37488/168641427-720f42fc-6d4a-4583-bd4f-4f37df8656c5.png)

**Comment by solalex1** [comment]
Обновился на последний dev+8f44132, 2022-05-17
Теперь при указании логина-пароля записываются парой, только у меня почему-то сначала password, потом user.
Но теперь вылез другой баг - при попытке удалить логин с паролем (записать пустые поля) - логин удаляется, а пароль нет.
А также не отображается пароль в поле  при установленной паре.
![2022-05-17_10-34-55](https://user-images.githubusercontent.com/20441408/168737171-d5f7fdd6-16f2-46fe-ac77-ad8b13488e43.png)
.

**Comment by solalex1** [comment]
Посмотрел код, предлагаю rtsp-password-plain убрать, а rtsp-password сделать type="password"
![2022-05-17_11-08-16](https://user-images.githubusercontent.com/20441408/168740744-fbc5be74-a20f-4d31-810c-7b343f3f0d8a.png)

**Comment by themactep** [comment]
> Обновился на последний dev+8f44132, 2022-05-17 Теперь при указании логина-пароля записываются парой, только у меня почему-то сначала password, потом user. 

Порядок полей не влияет на результат.

> Но теперь вылез другой баг - при попытке удалить логин с паролем (записать пустые поля) - логин удаляется, а пароль нет.

До сих пор не было запроса очищать установленные логин и пароль. Если есть такая необходимость, то я добавлю механизм удаления, но не через запись пустого поля, а через более явно выраженное намерение.

> А также не отображается пароль в поле при установленной паре.

Пароль и не должен светиться нигде после задания. В идеале он вообще должен шифроваться, как в случае с NETIP. Именно для этого и сделана пара полей (password, password-plain), которые работают в связке до момента успешной записи данных.

**Comment by solalex1** [comment]
> Именно для этого и сделана пара полей (password, password-plain), которые работают в связке до момента успешной записи данных.
Я правильно понимаю, что type="password" который сделан специально дя этого вы не хотите использовать, а используете  type="hiden" чтобы спрятать пароль? Который и так виден в коде? Который и так можно вытащить через веб консоль. Зачем? Тем более вход в веб запаролен.

**Comment by themactep** [comment]
Нет, неправильно. В нашу форму вводится пароль в открытом виде, но в конфиг записывается только результат его криптования (для RTSP сейчас нет, для NETIP делается именно так). Пароль шифруется на стороне клиента перед отправкой формы. Поэтому на камеру приходит поле password с уже сформированными данными. После отправки формы на сервере происходит валидация полей, и если что-то не проходит валидацию, то форма возвращается клиенту с заполнненными данными и просьбой исправить ошибку и переотправить данные. Чтобы вернуть форму для редактирования с оригинальным введенным паролем приходится сохранять его исходную форму до того момента, когда форма прошла валидацию, а данные успешно записаны. После этого пароля в явном виде не существует. Поэтому он не выводится назад в форму. Если можно только изменить, закриптовав и записав новый пароль.

Для RSTP сейчас это оверкил, поскольку пароль не шифруется для сохранения, просто копируется. Но такая реализация позволяет в любой момент ввести шифрование добавив лишь один вызов функции. К тому же, это гарантированно рабочая схема. Если она дает сбой, надо искать причину в связке браузер - камера. Какие-нибудь ошибки JS в консоли браузера есть при отправке формы?
