### ISSUE TITLE
При заходе на страницу /cgi-bin/preview-mjpeg.cgi браузер перестает отвечать

### ISSUE THREAD

**Issue by solalex1** [OpenIPC/microbe-web#46]
Проверено в Хроме, Опере, Яндекс-браузере.

**Comment by themactep** [comment]
На камере через ssh: `killall majestic; majestic`, и смотреть, что происходит с маждестиком во время открытия этой страницы.

**Comment by solalex1** [comment]
В лог начинают сыпать ошибки про медленную сеть
`10:54:07 [     sdk] log_venc_chn@1141             MJPEG 640x360 5fps 1024Kbit
10:54:07 [     sdk] create_vpss_chn@888             new venc: 3   vpss_grp: 0,   vpss_chn: 2
10:54:07 [     sdk] start_mjpeg@1358                mpeg_enc took 2052KB of MMZ [2040]
10:54:28 [   httpd] mjpeg_cb@564                  Slow network for MJPEG transmit, skipping data for 192.168.1.66:52010
10:54:28 [   httpd] mjpeg_cb@564                  Slow network for MJPEG transmit, skipping data for 192.168.1.66:52010
10:54:28 [   httpd] mjpeg_cb@564                  Slow network for MJPEG transmit, skipping data for 192.168.1.66:52010
10:54:29 [   httpd] mjpeg_cb@564                  Slow network for MJPEG transmit, skipping data for 192.168.1.66:52010
10:54:29 [   httpd] mjpeg_cb@564                  Slow network for MJPEG transmit, skipping data for 192.168.1.66:52010
`
сеть 100 мегабит без ошибок, потоки RTSP идут без проблем.

**Comment by widgetii** [comment]
Пропускная полоса для потока MJPEG на порядок больше потока H264/H265, который отдается через RTSP.

Можно увеличить размер внутреннего буфера ценой стабильности системы, но сомневаюсь, что есть смысл тратить время на эту проблему в 2022 году

**Comment by solalex1** [comment]
Тут даже проблема не в том что сети не хватает для  MJPEG 640x360 5fps 1024Kbit, а в том что браузер перестает реагировать и начинает выжирать память.

**Comment by widgetii** [comment]
Попробуйте увеличить буфер (чтобы пропали ошибки `Slow network`) и посмотреть, изменится ли ситуация

**Comment by solalex1** [comment]
> Попробуйте увеличить буфер (чтобы пропали ошибки `Slow network`) и посмотреть, изменится ли ситуация

имеется ввиду установка потока 1024Kbit? или что-то другое?

**Comment by widgetii** [comment]
Да, можно увеличивать значение в два раза и потом смотреть и т.д.

**Comment by solalex1** [comment]
> Да, можно увеличивать значение в два раза и потом смотреть и т.д.

Начал разбираться и выяснил, что проблема не в потоке, а именно в коде страницы /cgi-bin/preview-mjpeg.cgi
потому что просмотр mjpeg через http://ip/mjpeg.html идет нормально в браузере, и в логе нет Slow network

**Comment by themactep** [comment]
Я убрал со страницы превью javascript, который пытался сделать из mjpeg подобие mp4. Теперь показ mjpeg будет зависить только от поддержки браузером.

**Comment by solalex1** [comment]
> Я убрал со страницы превью javascript, который пытался сделать из mjpeg подобие mp4. Теперь показ mjpeg будет зависить только от поддержки браузером.

Теперь стало нормально, и браузер не виснет, и видео mjpeg показывает.
