### ISSUE TITLE
Импорт-экспорт конфигурации не работает 

### ISSUE THREAD

**Issue by fadermix** [OpenIPC/microbe-web#50]
Делаю экспорт конфигурации через веб интерфейс, импортирую на другую камеру (аналогичную, чтобы не прописывать всё вручную), при импорте появляется ошибка, мол конфиг аналогичный, то есть пустой.

Честно говоря не посмотрел содержимое файла, но кажется проблема именно в импорте, а не экспорте

**Comment by themactep** [comment]
Обновите WebUI из девелоперской ветки.
