### ISSUE TITLE
Не отображается обновление Majestic в прошивке hi3516cv300.

### ISSUE THREAD

**Issue by solalex1** [OpenIPC/microbe-web#52]
![2022-06-14_15-46-07](https://user-images.githubusercontent.com/20441408/173561471-33aa2f62-aa75-45c0-9d1f-273e0d2dab36.png)

**Comment by solalex1** [comment]
Не только на ubi не отображается, на squashfs то же самое. Железка hi3516cv300. web обновлен до последней девелоперской dev+c6b1c70, 2022-06-14

**Comment by themactep** [comment]
fixed in dev branch.
