### ISSUE TITLE
master+4b21bac, 2022-06-16 баги

### ISSUE THREAD

**Issue by solalex1** [OpenIPC/microbe-web#54]
Основной и очень неприятный момент - не восстанавливается конфигурация из сохраненного ранее конфига.
![2022-06-17_10-49-48](https://user-images.githubusercontent.com/20441408/174234014-a3409a48-25d3-40fc-b8f7-f30dd78cf6e8.png)
Второй баг - пропала настройка логина-пароля для rtsp, добавленная в предыдущей dev-версии
![2022-06-17_10-50-58](https://user-images.githubusercontent.com/20441408/174234210-4fe82845-3578-4ed4-b37c-1a72fe503136.png)

**Comment by solalex1** [comment]
Сломались настройки NTP
![2022-06-17_11-08-19](https://user-images.githubusercontent.com/20441408/174236144-3d39a395-5568-4ddd-8bdb-7615afc321ea.png)

**Comment by solalex1** [comment]
Файлы TZ и tzname были пустые и с нулевыми правами почему то. Удалил, пересоздал и заполнил. Теперь время показывает правильно, но изменить также не дает из веб.

**Comment by themactep** [comment]
1. Будем разбираться.
2. Логина и пароль на RTSP заменены на системные, отдельно больше не настраиваются.
3. Нажмите `Ctrl-F5` в браузере, чтобы перечитались скрипты и стили, они сейчас у вас из кэша берутся.

**Comment by themactep** [comment]
И, пожалуйста, одна бага -- один тикет.

**Comment by solalex1** [comment]
dev+f3bb2be, 2022-06-17
восстановление конфига заработало, спасибо.
