### ISSUE TITLE
Невозможно обновить majestic на новую версию через web.

### ISSUE THREAD

**Issue by solalex1** [OpenIPC/microbe-web#55]
Ругается на отсутствие места, хотя место есть.
![2022-06-17_15-20-10](https://user-images.githubusercontent.com/20441408/174280533-732141b5-33cb-4e4a-ad51-646214d1dd0e.png)
![2022-06-17_15-21-14](https://user-images.githubusercontent.com/20441408/174280558-d02af5f9-9e44-4df5-966b-6bd2ec3bedce.png)
![2022-06-17_15-21-54](https://user-images.githubusercontent.com/20441408/174280587-e05c03f3-f880-40bf-8538-1f561b982dc4.png)

**Comment by themactep** [comment]
Исправлено в dev.

**Comment by themactep** [comment]
Всё, нашел причину. Обновитесь из dev.

**Comment by esuslik** [comment]
Проблема сохраняется на ветке stable, таже сообщение что нет места. В dev ветке процесс обновления запускается, выводит прогресс и перезапускает камеру. Но при повторном входе показывает что Используется версия Majestic из прошивки.

**Comment by themactep** [comment]
Пришлите лог обновления.

**Comment by esuslik** [comment]
![image](https://user-images.githubusercontent.com/16290583/174425548-d6e3989d-67f6-4174-9edf-802d81345a81.png)

**Comment by esuslik** [comment]
кстати на stable проблема с недостатком песта прошла. Сейчас появилась кнопка установить обновление. Но также как на dev по факту не происходит обновление

**Comment by solalex1** [comment]
Проверил, на dev+00Fa2d1 обновление majestic проходит.
![2022-06-20_10-27-22](https://user-images.githubusercontent.com/20441408/174531165-c4dbefdc-838f-4cc0-95d8-3efc32480d66.png)
Но надпись что "Используется версия Majestic из прошивки." осталась

**Comment by esuslik** [comment]
тоде проверил, обновление происходит, но надпись остается

**Comment by themactep** [comment]
@widgetii, проверь, пожалуйста, запись в .meta на предмет экстра **d** в конце версии,
![extra-d](https://user-images.githubusercontent.com/37488/174569342-8778a611-d88d-49c8-a02b-86a8748bf0cb.png)

**Comment by widgetii** [comment]
В Majestic добавляется т.н. abbreviated commit hash, который извлекается командой `git log --pretty=format:'%h' -n 1` и состоит из 7 первых символов хэша, в meta файл добавляется из CI имя коммита, который генерируется командой `git rev-parse --short`, состоящий из 8 символов. Визуально мне казалось, что это одно и то же, но это не так.

Добавил в первую команду `--abbrev=8`, чтобы длина в обоих случаях была одинаковой (лучше больше, чем меньше)

**Comment by themactep** [comment]
@esuslik , если фикс решил проблему, то тикет можно коцнуть.

**Comment by esuslik** [comment]
обновление работает, только всегда показывает что используется версия из прошивки. Или так и должно теперь быть?
![image](https://user-images.githubusercontent.com/16290583/175779637-ab88c71e-8da3-4a08-850c-8f2a213b7a00.png)

**Comment by themactep** [comment]
В новой версии показываются оба возможных варианта установки и версия, доступная для обновления. Проверьте, что это работает на вашем сетапе.

![Screenshot from 2022-07-01 20-10-33](https://user-images.githubusercontent.com/37488/176979244-9d41ff22-0a27-4b85-8785-644b6ca8c3d7.png)

**Comment by esuslik** [comment]
вроде покахывает, но при нажатии обновить, в интерфейсе все без изменений. Непонятно что на покахывает доступную на гитхабе более свежую. А bundeled орстается прежней.
И какой момент будет покахывать что установлено в оверлей.

Вообще я запутался в полях. Какое что означает.
![изображение](https://user-images.githubusercontent.com/16290583/176986132-4f087f4a-370c-42b4-b927-b87820bdf4c5.png)

**Comment by themactep** [comment]
Bundled - это маджестик, который идет в составе прошивки. Эта версия будет с вами всегда, пока не обновится прошивка. In overlay - версия, установленная поверх той, что шла с прошивкой. Она как бы подменяет оригинальную. Если ее удалить, то станет снова доступна bundled. Последняя строка - доступная к установке версия на сервере в интернете. После успешной установки обновления версия в оверлее должна стать той же, что в онлайне (on GitHub). Если после обновления у вас все еще пишется not installed in overlay, значит или обновление не прошло, либо в скрипте ошибка.

**Comment by esuslik** [comment]
да, пишет not  installed
самое интересное что если после обновления зайти через ssh и посмотреть дату изменения majestic в папке /usr/bin/
то стоит Jul  1 16:48
То есть подозреваю что он фактически обновлен, а вот в веб об этом нет информации.

**Comment by themactep** [comment]
Какую версию покажет /usr/bin/majestic -v ? И есть ли на камере файл /overlay/usr/bin/majestic ?

**Comment by esuslik** [comment]
/usr/bin/majestic -v
master+55c12b6, 2022-07-01

ls -la /overlay/
total 0
drwxr-xr-x    5 root     root             0 Jan  1  1970 .
drwxr-xr-x    1 root     root             0 Jan  1  1970 ..
drwxr-xr-x    6 root     root             0 Jan  1  1970 root
drwxr-xr-x    3 root     root             0 Jan  1  1970 work

**Comment by esuslik** [comment]
/overlay/root/usr/bin/majestic -v
master+55c12b6, 2022-07-01

**Comment by themactep** [comment]
Проблема понятна. Думаю над вариантом решения.

**Comment by themactep** [comment]
Вариант найден. Пробуйте свежий апдейт.

**Comment by esuslik** [comment]
тепрь показывает корректно что установлено в оверлэй и правильная версия. Но начало справа писать что недостаточно места. То есть обновить на новую кнопки нет.

![изображение](https://user-images.githubusercontent.com/16290583/176997176-803e831c-20d6-41ee-bf4a-886a91a2e1f5.png)

**Comment by themactep** [comment]
добавил подробную информацию о свободном месте. давайте искать, куда оно девается на вашей камере :)

**Comment by esuslik** [comment]
кажется место есть, но может веб не так его считает?
![изображение](https://user-images.githubusercontent.com/16290583/177001542-81074231-d56f-47eb-b3f2-e89f04632886.png)
![изображение](https://user-images.githubusercontent.com/16290583/177001560-8480d7a7-5883-4b43-8a41-cd182e7bdd82.png)

**Comment by themactep** [comment]
Ага, вижу, что скрипт ищет пустое место не там. Поправил. Сейчас должно заработать.

**Comment by esuslik** [comment]
да, теперь есть кнопка и на место не ругается. Жду когда выйдет обновление и попробую обновить через веб

**Comment by esuslik** [comment]
при нажатии на кнопку обновить получаю ошибку 
Страница недоступнаСайт 10.199.200.227 не отправил данных.
ERR_EMPTY_RESPONSE

в консколь такое:
httpd -p 85 -f -c /etc/httpd.conf
sh: check_url: out of range
/bin/sh: syntax error: bad substitution
sh: check_url: out of range
/bin/sh: syntax error: bad substitution
sh: check_url: out of range
/bin/sh: syntax error: bad substitution

**Comment by themactep** [comment]
попробуйте новый фикс.

**Comment by esuslik** [comment]
обновление встало. 
Нет лога о процессе обновления и после обновления, камера не перезагружается автоматом. Это так задумано?

**Comment by themactep** [comment]
Лога нет потому что там нечего выводить. Вся операция обновления теперь - это [одна команда](https://github.com/OpenIPC/microbe-web/blob/ffb45dd95b5105d520eddf69ee701a93e9edebf4/files/var/www/cgi-bin/majestic.cgi#L45).

Камеру перегружать после обновления маджестика нет смысла, а вот стартануть маджестик надо. Сейчас добавлю команду.

**Comment by themactep** [comment]
Сделал через отправку камеры в ребут, чтобы не городить костылей для поддержки разных имен скриптов. Тестируйте.

**Comment by esuslik** [comment]
вроде все работает, думаю можно закрывать тикет
