### ISSUE TITLE
Показывать какая стоит версия веб интерфейса и сохранять предыдущее значение

### ISSUE THREAD

**Issue by esuslik** [OpenIPC/microbe-web#57]
Сейчас по умолчанию какнал обновления веб интерфейса показывает пустое поле.
Есть возможность сделать чтобы показывалась та ветка которая установлена?

![image](https://user-images.githubusercontent.com/16290583/174425483-ea85c7bb-40ba-4c0d-95b1-dafde0483886.png)

**Comment by themactep** [comment]
Версии интерфейса (установленную и две доступные) видно в данных над селектом. Предустанавливать какую-либо из версий в селекте я не вижу смысла. Обновление должно быть осознанным актом, с явным выражением своих намерений: что именно пользователь собирается установить.

**Comment by esuslik** [comment]
там вроде и так надо сначала зайти в раздел прошивка, нажать кнопку установить, потом согласиться что точно уверен. Это вроде подтверждает явные намерения.

При установленом канале это будет на 2 клика меньше.

**Comment by themactep** [comment]
добавлено в девелоперской ветке.
