### ISSUE TITLE
Раздел настройки majestic на каждой вкладке выставить нужные настройки и одной кнопкой применить весь конфиг

### ISSUE THREAD

**Issue by esuslik** [OpenIPC/microbe-web#58]
В новом интерфейсе настроек majestic появилась проблема, что в каждом разделе настроек необходимо нажимать кнопку сохранить, потом снова переходить в меню -- настройки majestic -- выбирать раздел -- ставить галки\настройки и применять конфигурацию и все по новой для каждого раздела. Тратит много времени если настраивать много камер или если сбрасывать в заводские.

На старом интерфейсе было удобно что открыл окно, проставил все галки\настройки и одной кнопкой нажал применить конфигурацию.

**Comment by themactep** [comment]
Для массового изменения параметров настройте нужную конфигурацию один раз, сделайте экспорт в файл, потом загружайте готовый конфиг.

**Comment by esuslik** [comment]
так и делаю. Нол когда надо сбосить камеру или настроить несколько разных камер с разынми конфигами, тогда приходится много раз перетыкивать разделы.

Может как вариант можно сделать чтобы после нажатия сохранить нас бы викидывало обратно в тот же раздел, чтобы можно было выбрать сразу следующий?

**Comment by themactep** [comment]
Версия в девелоперской ветке возвращает на ту же страницу. Но там могут быть другие баги :)

**Comment by themactep** [comment]
В девелоперской ветке добавлена возможность править все настройки на одной странице. Неудобно и медленно, как просили.
