### ISSUE TITLE
Предпросмотр video не работает если не включен HLS

### ISSUE THREAD

**Issue by esuslik** [OpenIPC/microbe-web#59]
Предпросмотр video не работает если не включен HLS, но если мы включаем HLS то тогда просмотр видео доступен всем подряд на 80 порту.

Возможно ли реализовать чтобы администратор который настраивает камеру мог видеть предпросмотр только авторизовавшись на камере. Но чтобы видео не было доступно всем подряд на 80 порту?

**Comment by themactep** [comment]
Отключите HLS в настройках маджестика, это уберет трансляцию с 80 порта. Превью останется доступно из веб интерфейса при включеной поддержке хотя ба одного из фоматов: JPEG/MJPEG/MPEG4(Video0).

**Comment by esuslik** [comment]
На ветке stable
все отключено, кроме Video0 и Video1
Предпросмотр не работает. 

На ветке dev предпросмотр работает только в разделе mjpeg

При открытии url видео http://10.199.200.175/video.mp4  не открывает и постоянно крутит щакгрузку в браузере

![изображение](https://user-images.githubusercontent.com/16290583/175779813-9eff953f-0275-429f-9e6e-a3bce5a7dd90.png)

**Comment by themactep** [comment]
Если /video.m4 не гонит видео, и при этом video0 включен, то надо смотреть на вывод маджестика. Это уже не к вебу вопросы.

@widgetii, это может быть проблемой отсутствия кодека в браузере?

**Comment by widgetii** [comment]
Если HLS выключен, то mp4 недоступен by design
