### ISSUE TITLE
Если очистить поле "шлюз", то сеть пропадает

### ISSUE THREAD

**Issue by vukitoso** [OpenIPC/microbe-web#60]
Здравствуйте.
Заметил баг один на прошивке от 16 июня: если через веб интерфейс в сетевых настройках очистить поле шлюза и сохранить, то невозможно будет подключиться к камере по ip адресу. Сеть пропадает.

Хотя по логике наличие шлюза не обязательно для функционирования камеры в сети.

После сохранения в файле /etc/network/interfaces строка со шлюзом была просто без значения, вот так:
gateway

**Comment by themactep** [comment]
Как вы смогли записать значения формы с пустым параметром? В скрипте стоит проверка на пустое значение. Форма должна была вернуться с сообщением об ошибке.

**Comment by vebmaster** [comment]
Последовательность действий: стираем поле шлюз и днс1 дна2 например, жмём сохранить, перезагружаем камеру - сеть отсутствует, камера недоступна.

**Comment by themactep** [comment]
опробуйте изменения в свежей версии в девелоперской ветке.
