### ISSUE TITLE
[feature] Add password recovery or reminder via Telegram 

### ISSUE THREAD

**Issue by mariarti** [OpenIPC/microbe-web#62]
Please consider the option of recovering / reminding the password (or something else) via telegram.

**Comment by themactep** [comment]
Проблема в том, что пароль закрывает доступ к исполняемым файлам (CGI) на уровне сервера. Поэтому без пароля нельзя инициализировать исполнение скрипта для отсылки пароля в Телеграм. Замкнутый круг.

**Comment by themactep** [comment]
not feasible.
