### ISSUE TITLE
Применить настройки majestic ломает запуск majestic

### ISSUE THREAD

**Issue by esuslik** [OpenIPC/microbe-web#63]
В dev ветке в настройках маджестика в разделе osd нажимаем сохранить. После сохраненния majestic больше не стартует.
Проблема на сколько я понял в том что не заполнено поле или не записывается значение по умолчанию 'template' in section 'osd'.

11:38:24 [    main] main@132                      Majestic Lite for HiSilicon, version master+b2f921b, built on 2022-06-22
11:38:24 [app_conf] load_config@111               Using /etc/majestic.yaml as main configuration
11:38:24 [app_conf] parse_app_config@318          Main audio codec is opus (other options: mp3, aac, pcm, alaw, ulaw)
11:38:24 [  config] parse_param_value@155         Can't find 'template' in section 'osd'.

**Comment by themactep** [comment]
поправлено в девелоперской ветке.
