### ISSUE TITLE
Поле audio sample rate не дает поставить значение 48000

### ISSUE THREAD

**Issue by esuslik** [OpenIPC/microbe-web#64]
Поле audio sample rate не дает поставить значение 48000, оно применимо для камер
hi3516ev300 (hi3516ev300 family), imx335, 16 MB Flash, 2.2.07.01-lite,

![изображение](https://user-images.githubusercontent.com/16290583/177304995-4e0a7ce6-a50b-4879-9491-4f0dd3dcd1a5.png)

**Comment by themactep** [comment]
увеличил верхний порог до 96k
