### ISSUE TITLE
Раздел обновление majestic показывает что все обновлено, хотя есть новые версии

### ISSUE THREAD

**Issue by esuslik** [OpenIPC/microbe-web#65]
Всегда показывает что все обновлено, что не дает обновить overlay или вернуть к версии из прошивки
![изображение](https://user-images.githubusercontent.com/16290583/178644319-0d2c01f5-b5f7-4e99-8976-16e64595342d.png)

**Comment by themactep** [comment]
нужен тест последней версии. надеюсь, что поправил.

**Comment by esuslik** [comment]
либо обнолений не ьбыло с 15 числа, либо что-то не так работает
![изображение](https://user-images.githubusercontent.com/16290583/179772995-d6640250-6cef-4189-8134-e195137ba0bd.png)

**Comment by themactep** [comment]
Последняя сборка была 15, все верно.

**Comment by esuslik** [comment]
Проверил на другой камере, обновление в оверлэй работает.
Но когда версия самая свежая, нет кнопки вернуться на версию из прошивки. Если она старше.
Я этим функуцогналом не пользуюсь, но может это кому-то важно

**Comment by themactep** [comment]
в новой версии должно работать.

**Comment by themactep** [comment]
если работает - тикет можно коцнуть.
