### ISSUE TITLE
секция Image не отрабатывает поворот кадра

### ISSUE THREAD

**Issue by Melckor** [OpenIPC/microbe-web#66]
при включении поворота кадра на 90 градусов в web остаётся 0

![micro-web image](https://user-images.githubusercontent.com/93010796/180980697-068cdc1a-5360-4771-82f4-e1524855ce25.png)

при включении поворота перестаёт работать отображение видео
![prewiev](https://user-images.githubusercontent.com/93010796/180980938-bc0deb82-dc06-4ba5-9fce-4b8b24c8f967.jpg)

возврат поворота кадра в 0 включает изображение с камеры.

**Comment by Melckor** [comment]
> при включении поворота кадра на 90 градусов в web остаётся 0 отображение видео 
![micro-web image](https://user-images.githubusercontent.com/93010796/180980697-068cdc1a-5360-4771-82f4-e1524855ce25.png) 
при включении поворота перестаёт работать 
![prewiev](https://user-images.githubusercontent.com/93010796/180980938-bc0deb82-dc06-4ba5-9fce-4b8b24c8f967.jpg)

**Comment by themactep** [comment]
попробуй новую версию.

**Comment by Melckor** [comment]
Спасибо, теперь всё коректно отображаем gui.
