### ISSUE TITLE
не работает плагин, Яндекс Диск

### ISSUE THREAD

**Issue by Melckor** [OpenIPC/microbe-web#67]
не работает отправка (вручную) снапов в Яндекс диск
![yadisk](https://user-images.githubusercontent.com/93010796/180982116-d07f296f-a672-465f-96f2-570448fd558e.jpg)

**Comment by ystinia** [comment]
**Решение**
_Оказалось, что проблема в пароле. Я использовал некорректный пароль: для монтирования яндекс диска указанным выше способом необходимо создать новый пароль для приложения.
То есть необходимо зайти в яндекс паспорт (или как-то так) и создать отдельный пароль для приложения (выбрать webdav), после чего использовать для монтирования его. У меня проблема решилась_

**Comment by ZigFisher** [comment]
Возможно стоит в дескрипшене плагина на Яндекс указать этот нюанс кратко...
