### ISSUE TITLE
Incorrect 'false' parameter specified for 'system.webAdmin'

### ISSUE THREAD

**Issue by widgetii** [OpenIPC/microbe-web#68]
Just turned out when webui saves config file it set `webAdmin: false`

But it can be only `enabled` or `disabled`. My suggestions are: either fix it in webui, or change to boolean type in Majestic

**Comment by themactep** [comment]
What branch do you use? There is a fix for that in dev. https://github.com/OpenIPC/microbe-web/blob/05aa4f63374d79b21a5ca81fdc4692ac8b66707c/files/var/www/cgi-bin/majestic-settings.cgi#L47

**Comment by widgetii** [comment]
Camera was from the master. Thanks, fixed
