### ISSUE TITLE
не работает плагин, отправка на email Яндекс Почта

### ISSUE THREAD

**Issue by Melckor** [OpenIPC/microbe-web#69]
камера HS303 v2 [hi3518ev200]
не работает плагин отправки на email

**Comment by themactep** [comment]
"Дорогие ученые. У меня который год в подполе происходит подземный стук. Объясните, пожалуйста, как он происходит".

Подробности будут?

**Comment by Melckor** [comment]
Решение, по проблеме не работы с Яндекс Почта.
---
Для настройки паролей приложений перейдите в Яндекс.Паспорт (https://passport.yandex.ru/profile) нажмите на «Включить пароли приложений». 
При включении паролей приложения система попросит Вас ввести действующий пароль от учетной записи. 
Затем нажмите кнопку «Создать новый пароль» и выберите раздел «Диск» и введите имя для пароля.
сформированный пароль вставьте в форму плагина «SMTP server password»
Далее в аккаунте вашей почты переходите: Почта → Все настройки → Почтовые программы
включите чекбоксы "С сервера imap.yandex.ru по протоколу IMAP" и "Способ авторизации по IMAP"
![yaemail](https://user-images.githubusercontent.com/93010796/181079055-8d6afbf4-7aae-4806-afbb-4dc76ba6be89.jpg)
