### ISSUE TITLE
Rename the repository branches

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/microbe-web#7]
Rename the repository branches to "stable" and "development" to match the menu items in the web interface.

**Comment by ZigFisher** [comment]
It will also be necessary to correct the links to perform synchronization and update actions.

**Comment by themactep** [comment]
done.

**Comment by themactep** [comment]
debug_microbe in /etc/profile needs corrections to follow the changes.

**Comment by ZigFisher** [comment]
Done
