### ISSUE TITLE
Hide some menu sections for processors that do not support features

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/microbe-web#70]
Make the "motion detection" plugin available only on Hisilicon and Goke processors. 
Make an exception for series processors in V1 (no motion detect).
Thanks !

**Comment by widgetii** [comment]
Two HiSilicon families have no hardware motion detection: hi3516cv100 and hi3516av100

**Comment by themactep** [comment]
I left the menu section but restricted access to the page with a stop list of processor families. https://github.com/OpenIPC/microbe-web/blob/4e2559e5c28d2eacd95dbc65c456f93f644b9316/files/var/www/cgi-bin/plugin-motion.cgi#L9

**Comment by ZigFisher** [comment]
Hide h264 codec selector for hi3516cv200 processor group (and hi3516cv100 group)

**Comment by themactep** [comment]
done.
