### ISSUE TITLE
Нет возможности указать smtp авторизацию в Notify Yucca

### ISSUE THREAD

**Issue by jidckii** [OpenIPC/microbe-web#72]
### Описание

Нет возможности указать smtp авторизацию в **Notify Yucca**
По умолчанию авторизация выключена, но если её включить, настроить в этом блоке уже не получится и придётся использовать стандартную отправку письма.

```sh
./yucca server --help | grep -A5 "SMTP Server Flags"
SMTP Server Flags:
      --smtp-server                                      Enable SMTP server (default true)
      --smtp-server-listen-address string                Interface and port for the built-in SMTP server (default "0.0.0.0:1025")
      --smtp-server-password string                      Password to use for authentication on SMTP server
      --smtp-server-read-timeout duration                Timeout for reading incoming message (default 1s)
      --smtp-server-username string                      Username to use for authentication on SMTP server
```

### Логи и/или скриншоты

![image](https://user-images.githubusercontent.com/6608896/181433106-96cfb0e5-d2b0-4ca5-bd5e-11f62fdc93ca.png)

### Версия microbe-web

dev+20e554c, 2022-07-27

**Comment by themactep** [comment]
нет плагина - нет проблемы.
