### ISSUE TITLE
[request] zerotier-one plugin

### ISSUE THREAD

**Issue by cronyx** [OpenIPC/microbe-web#79]
Сервис присутствует только с сборках **ultimate**, соответственно перед попыткой настройки необходимо проверить fw build или наличие в системе бинаря zerotier-one.

Процесс соединения выглядит следующим образом:

1. Активация демона:
```
echo "daemon=1" > /etc/zerotier.conf
/etc/init.d/S90zerotier start
```
2. Регистрация на сервисе my.zerotier.com и получение 16-ти значного network id (пример: a1cbf4b62a41da0f). Этот шаг делается юзером самостоятельно, но можно каким-то сообщением напомнить ему об этом, типа сходи на https://my.zerotier.com и зарегистрируйся.
3. На странице плагина вводится network id и жмется кнопка подключения. Подключение выполняется:
```
zerotier-cli join a1cbf4b62a41da0f
```
если подключение успешно, в ответ приходит статус:
```
200 join OK
```
либо другой код в случае ошибки.

4. После получения ответа об успехе, в **/var/lib/zerotier-one/networks.d/** автоматически формируется конфиг с состоянием подключения (**a1cbf4b62a41da0f.conf**, где имя - это network id):
```
v=0000000000000007
nwid=a1cbf4b62a41da0f
ts=00000182538b7a8a
ctmd=00000000001b7740
r=0000000000000012
id=e1e1030dab
tt=0000000000
tl=0000000000000000
f=0000000000000002
ml=0000000000000020
t=0000000000000000
n=cronyx
mtu=0000000000000af0

```
Из конфига нам необходимо получить **nwid** (network id) и **n** (name [имя сети заданное при регистрации на сервисе my.zerotier.com]) и отобразить на странице плагина вместе с успешным состоянием соединения + кнопка отключиться от сети. 

5. Процесс отключения выглядит следующим образом:
```
zerotier-cli leave a1cbf4b62a41da0f
```
если отключение успешно, в ответ приходит статус:
```
200 leave OK
```
конфиги состояния из **/var/lib/zerotier-one/networks.d/** удаляются автоматически при выходе из сети, пользователя необходимо вернуть на изначальную страницу ввода network id.

6. При сбросе настроек (Reset) необходимо делать выход из сети (**zerotier-cli leave nwid**), остановку сервиса, (**/etc/init.d/S90zerotier stop** или **killall zerotier-one**) и деактивацию демона (**echo "daemon=0" > /etc/zerotier.conf**)

**Comment by themactep** [comment]
Красава! По такому описанию одно удовольствие писать код. Я уже почти доделал плагин. Завтра прлшью камеру на 16М, залью ultimate и отлажу старт/стоп на живой системе.

**Comment by cronyx** [comment]
Я ценю твое время, поэтому максимально подробное ТЗ :)

**Comment by themactep** [comment]
@cronyx, надо что-то еще менять в плагине или можно закрывать тикет?

**Comment by cronyx** [comment]
Закрывай, я пока не могу изложить улучшайзинги, к сожалению нет вермени, как только появится, я пепероткрою и дополню если можно.

**Comment by themactep** [comment]
ok, как будешь готов - открывай снова.
