### ISSUE TITLE
Collection of wishes and recommendations on the OpenWall service plugin

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/microbe-web#86]

**Comment by ZigFisher** [comment]
Make the interval in minutes fixed - 15, 30, 60
Arbitrary spacing must be disabled
The default value is 15 minutes

**Comment by ZigFisher** [comment]
Add a fixed length field for description or location.
Data must be transferred along with the snapshot

**Comment by themactep** [comment]
done. [fcb8e954549e6fedd4aba9e584e466cf172669ec]
