### ISSUE TITLE
После переезда настроек в основное меню majestic не входят все пункты и невозможно прокрутить

### ISSUE THREAD

**Issue by esuslik** [OpenIPC/microbe-web#89]
В мееню настроек majestic невозможно прокрутить вних чтобы выбрать все настройки которые не уместились в экран.
hidpi экран, разрешение 1920х1080 с масштабирование 150%

![image](https://user-images.githubusercontent.com/16290583/183087113-5665d24b-9c17-4370-b82f-eccb796081f9.png)

**Comment by themactep** [comment]
добавил дополнительное меню внутри страницы настроек маждестика.
