### ISSUE TITLE
Сделать выбор расположения OSD на кадре

### ISSUE THREAD

**Issue by Melckor** [OpenIPC/microbe-web#97]
Предлагаю сделать выбор через меню в web местоположение OSD в кадре, в следующих стандартных местах:
1. верхний левый угол  
2. нижний левый угол
3. правый верхний угол
4. нижний левый угол
с регулируемым отступом от края в 15 пикселей.

**Comment by widgetii** [comment]
posX, posY могут быть как положительными числами (считается отступ от левого и верхнего края), так и отрицательными (отсчет производится от правого и нижнего), но они должны быть четными числами из-за ограничения платформы

**Comment by themactep** [comment]
Окей, это уже можно реализовать через веб.

**Comment by Melckor** [comment]
Тогда ждём релиза

**Comment by Melckor** [comment]
при выборе расположения не сохраняется параметр OSD preset position, 
он всегда после сохранения становится "Select from available options"
если изменить координаты который по умолчанию для сторон левый низ, правый верх, правый низ, то после сохранения OSD перемещается в левый верх.

**Comment by themactep** [comment]
пресет и не должен сохраняться. это просто фича в интерфейсе для выставления готовых координат для размещения osd по углам. выбор угла меняет координаты в полях, они и сохраняются.
