### ISSUE TITLE
Отправка на email не срабатывает. Не передается корректно параметр username в скрипте send2email.sh

### ISSUE THREAD

**Issue by esuslik** [OpenIPC/microbe-web#98]
Прописаны настройки email для отправки:
email_enabled="true"
email_attach_snapshot="false"
email_from_name="warn@it.ru"
email_from_address="warn@it.ru"
email_to_name="srv@it.ru"
email_to_address="srv@it.ru"
email_subject="Motion detected"
email_body="detected"
email_smtp_host="smtp.yandex.ru"
email_smtp_port="465"
email_smtp_username="warn@it.ru"
email_smtp_password="ываывапы"
email_smtp_use_ssl="true"
email_socks5_enabled=""

В консоли при запуске скрипта /usr/sbin/send2email.sh
Получаем команду curl --silent --verbose --connect-timeout 100 --max-time 100 --ssl --url smtps://smtp.yandex.ru:465 --mail-from warn@it.ru --mail-rcpt srv@it.ru --user ':ываывапы' --upload-file /tmp/email.1456.txt

В параметре --user ':ываывапы' пропущен username до двоеточия

**Comment by themactep** [comment]
please test the fix and close the ticket if it works for you.

**Comment by esuslik** [comment]
Работает, спасибо
